services:
  - type: web
    name: web
    plan: free
    runtime: docker
    dockerfilePath: ./web/Dockerfile
    dockerContext: ./web
  - type: web
    name: api
    plan: free
    runtime: docker
    dockerfilePath: ./api/Dockerfile
    dockerContext: ./api
